import type { ServiceSlug } from "./services";

/**
 * The scroll-built hero: one illustrated building taken from derelict shell
 * to open for business, one Mayfair service per stage.
 *
 * Frames live in /public/sequence/{sm,lg}/NNN.webp and are generated by
 * scripts/build-sequence.sh from the keyframe + transition renders.
 * The building is an AI-generated illustration, not a Mayfair project.
 */
export const sequence = {
  frameCount: 81,
  framesPerStage: 16,
  sizes: {
    sm: { width: 768, height: 430 },
    lg: { width: 1440, height: 806 },
  },
  src: (size: "sm" | "lg", index: number) => `/sequence/${size}/${String(index).padStart(3, "0")}.webp`,
} as const;

const step = sequence.framesPerStage;

export type Stage = {
  /** Frame index the stage settles on. */
  frame: number;
  label: string;
  title: string;
  text: string;
  services: ServiceSlug[];
};

export const stages: Stage[] = [
  {
    frame: 0,
    label: "Before",
    title: "A tired building.",
    text: "Cracked render, boarded windows, no power. The kind of job that needs more than one trade.",
    services: [],
  },
  {
    frame: step,
    label: "Restore",
    title: "Made sound again.",
    text: "Scaffold up, damaged render cut out and replaced. Forklifts, mixers and compactors on site — the same kind of machines Mayfair hires out.",
    services: ["restoration", "equipment-hire"],
  },
  {
    frame: step * 2,
    label: "Fit out",
    title: "Divided and wired.",
    text: "New partitions frame the rooms. Power points and lighting go in for each room.",
    services: ["office-partitioning", "electrical"],
  },
  {
    frame: step * 3,
    label: "Finish",
    title: "Finished inside and out.",
    text: "Walls painted, floors carpeted, rooms ready to use.",
    services: ["painting", "carpeting"],
  },
  {
    frame: step * 4,
    label: "Install",
    title: "The specialist work.",
    text: "An ATM set into the wall. An EV charger in the bay. Infrastructure, fitted on site.",
    services: ["atm-installation", "ev-charging"],
  },
  {
    frame: step * 5,
    label: "Open",
    title: "Open for business.",
    text: "One contractor for every trade on this list. Based in Gaborone, working across Botswana.",
    services: [],
  },
];
